from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QVBoxLayout
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar


class PlotWidget(QtWidgets.QWidget):
    def __init__(self, parent=None, w=400, h=350, toolbar=False):
        super().__init__(parent)

        self.fig, self.ax = plt.subplots()
        self.canvas = FigureCanvas(self.fig)
        self.lay = QVBoxLayout(self)
        if toolbar:
            self.toolbar = NavigationToolbar(self.canvas, self)
            self.lay.addWidget(self.toolbar)
        self.lay.addWidget(self.canvas)

        self.line, *_ = self.ax.plot([])

        self.setLayout(self.lay)
        self.setFixedSize(w, h)

    def update_plot(self, data):
        self.line.set_data(range(len(data)), data)

        self.ax.set_xlim(0, len(data))
        self.ax.set_ylim(min(data), max(data))
        self.fig.tight_layout()
        self.canvas.draw()


class MainWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__(self)
        self.initUI()

    def initUi(self):
        self.setObjectName("MainWindow")
        self.resize(931, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphWidget = PlotWidget()
        self.graphWidget.setGeometry(QtCore.QRect(20, 70, 511, 551))
        self.graphWidget.setObjectName("graphWidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.graphWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timeSlider = QtWidgets.QSlider(self.graphWidget)
        self.timeSlider.setGeometry(QtCore.QRect(0, 527, 509, 20))
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.anomaliesWidget = QtWidgets.QWidget(self.centralwidget)
        self.anomaliesWidget.setGeometry(QtCore.QRect(590, 150, 331, 471))
        self.anomaliesWidget.setObjectName("anomaliesWidget")
        self.BButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.BButton.setEnabled(False)
        self.BButton.setGeometry(QtCore.QRect(80, 250, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.BButton.setFont(font)
        self.BButton.setObjectName("BButton")
        self.plusButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.plusButton.setEnabled(False)
        self.plusButton.setGeometry(QtCore.QRect(80, 190, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.SButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.SButton.setEnabled(False)
        self.SButton.setGeometry(QtCore.QRect(80, 310, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.SButton.setFont(font)
        self.SButton.setObjectName("SButton")
        self.nButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.nButton.setEnabled(False)
        self.nButton.setGeometry(QtCore.QRect(200, 190, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.nButton.setFont(font)
        self.nButton.setObjectName("nButton")
        self.RButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.RButton.setEnabled(False)
        self.RButton.setGeometry(QtCore.QRect(200, 250, 51, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.RButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.RButton.setFont(font)
        self.RButton.setObjectName("RButton")
        self.QButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.QButton.setEnabled(False)
        self.QButton.setGeometry(QtCore.QRect(200, 310, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.QButton.setFont(font)
        self.QButton.setObjectName("QButton")
        self.FButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.FButton.setEnabled(False)
        self.FButton.setGeometry(QtCore.QRect(80, 130, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.FButton.setFont(font)
        self.FButton.setObjectName("FButton")
        self.jButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.jButton.setEnabled(False)
        self.jButton.setGeometry(QtCore.QRect(200, 130, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.jButton.setFont(font)
        self.jButton.setObjectName("jButton")
        self.VButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.VButton.setEnabled(False)
        self.VButton.setGeometry(QtCore.QRect(80, 70, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.VButton.setFont(font)
        self.VButton.setObjectName("VButton")
        self.AButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.AButton.setEnabled(False)
        self.AButton.setGeometry(QtCore.QRect(200, 70, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.AButton.setFont(font)
        self.AButton.setObjectName("AButton")
        self.anomLabel = QtWidgets.QLabel(self.anomaliesWidget)
        self.anomLabel.setEnabled(True)
        self.anomLabel.setGeometry(QtCore.QRect(0, 10, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.anomLabel.setFont(font)
        self.anomLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.anomLabel.setAutoFillBackground(False)
        self.anomLabel.setTextFormat(QtCore.Qt.PlainText)
        self.anomLabel.setScaledContents(False)
        self.anomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.anomLabel.setObjectName("anomLabel")
        self.tachyButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.tachyButton.setEnabled(False)
        self.tachyButton.setGeometry(QtCore.QRect(20, 400, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.tachyButton.setFont(font)
        self.tachyButton.setObjectName("tachyButton")
        self.bradyButton = QtWidgets.QPushButton(self.anomaliesWidget)
        self.bradyButton.setEnabled(False)
        self.bradyButton.setGeometry(QtCore.QRect(200, 400, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.bradyButton.setFont(font)
        self.bradyButton.setObjectName("bradyButton")
        self.optionsWidget = QtWidgets.QWidget(self.centralwidget)
        self.optionsWidget.setGeometry(QtCore.QRect(20, 20, 511, 51))
        self.optionsWidget.setObjectName("optionsWidget")
        self.analysisButton = QtWidgets.QPushButton(self.optionsWidget)
        self.analysisButton.setEnabled(True)
        self.analysisButton.setGeometry(QtCore.QRect(340, 0, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.analysisButton.setFont(font)
        self.analysisButton.setMouseTracking(True)
        self.analysisButton.setObjectName("analysisButton")
        self.widget = QtWidgets.QWidget(self.optionsWidget)
        self.widget.setGeometry(QtCore.QRect(-1, 0, 271, 51))
        self.widget.setObjectName("widget")
        self.ageEdit = QtWidgets.QTextEdit(self.widget)
        self.ageEdit.setGeometry(QtCore.QRect(160, 20, 104, 31))
        self.ageEdit.setObjectName("ageEdit")
        self.filepathEdit = QtWidgets.QTextEdit(self.widget)
        self.filepathEdit.setGeometry(QtCore.QRect(10, 20, 104, 31))
        self.filepathEdit.setObjectName("filepathEdit")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(160, 0, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.valuesWidget = QtWidgets.QWidget(self.centralwidget)
        self.valuesWidget.setGeometry(QtCore.QRect(610, 20, 311, 121))
        self.valuesWidget.setObjectName("valuesWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.valuesWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 311, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.maxBPMDial = QtWidgets.QDial(self.gridLayoutWidget)
        self.maxBPMDial.setEnabled(False)
        self.maxBPMDial.setObjectName("maxBPMDial")
        self.gridLayout.addWidget(self.maxBPMDial, 1, 1, 1, 1)
        self.signalQualityDial = QtWidgets.QDial(self.gridLayoutWidget)
        self.signalQualityDial.setEnabled(False)
        self.signalQualityDial.setObjectName("signalQualityDial")
        self.gridLayout.addWidget(self.signalQualityDial, 0, 1, 1, 1)
        self.sQLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.sQLabel.setFont(font)
        self.sQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sQLabel.setObjectName("sQLabel")
        self.gridLayout.addWidget(self.sQLabel, 0, 0, 1, 1)
        self.maxBPMLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.maxBPMLabel.setFont(font)
        self.maxBPMLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.maxBPMLabel.setObjectName("maxBPMLabel")
        self.gridLayout.addWidget(self.maxBPMLabel, 1, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BButton.setText(_translate("MainWindow", "B"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.SButton.setText(_translate("MainWindow", "S"))
        self.nButton.setText(_translate("MainWindow", "n"))
        self.RButton.setText(_translate("MainWindow", "R"))
        self.QButton.setText(_translate("MainWindow", "Q"))
        self.FButton.setText(_translate("MainWindow", "F"))
        self.jButton.setText(_translate("MainWindow", "j"))
        self.VButton.setText(_translate("MainWindow", "V"))
        self.AButton.setText(_translate("MainWindow", "A"))
        self.anomLabel.setText(_translate("MainWindow", "DETECTED ANOMALIES"))
        self.tachyButton.setText(_translate("MainWindow", "TACHYCARDIA"))
        self.bradyButton.setText(_translate("MainWindow", "BRADYCARDIA"))
        self.analysisButton.setText(_translate("MainWindow", "ANALYSIS"))
        self.label.setText(_translate("MainWindow", "File Path"))
        self.label_2.setText(_translate("MainWindow", "Patient\'s Age"))
        self.sQLabel.setText(_translate("MainWindow", "SIGNAL QUALITY"))
        self.maxBPMLabel.setText(_translate("MainWindow", "MAX BPM"))
